### ISSUE TITLE
[Bug] Ctrl+Tab Double Analyze Wrong Score

### ISSUE THREAD

**Issue by NybyDK** [AAU-SW7-PSAAAB/energy-label-extension#108]
When scanning a website and ctrl+tabbing to another website, it scans both and mixes the scores into one, for example, 38 format results in 100/100 website with a red circle hehe

I think it is because of this:

```js
window.addEventListener("load", () => {
	browser.runtime.sendMessage({ action: MessageLiterals.SiteLoaded });
});
```

in content.ts

**Comment by KamyaPA** [comment]
I cannot recreate the bug in either firefox or chromium
When alt tabbing it finishes the scan of the previous webpage and shows me the that score.

**Comment by DenFlyvendeGed** [comment]
Anton sige at der her issue passer godt sammen med dette:
Extension state should be tab based, such that the extension is ready to scan when accesing a new tab, rather than showing ressults of other tabs
