### ISSUE TITLE
Find sources and define scoring system

### ISSUE THREAD

**Issue by AlbertHald** [AAU-SW7-PSAAAB/energy-label-extension#11]
The plugins need to be defined. We need to find sources about the problems we want to fix.

Following need to be known for each plugin:

- Problem which is being fixed
- Some source on the severity of the problem (Preferably compared to others)
- A detailed description of the problem
- A detailed description of how to fix the problem

**Comment by AlbertHald** [comment]
The plugins need to be defined. We need to find sources about the problems we want to fix.

Following need to be known for each plugin:
- Problem which is being fixed
- Some source on the severity of the problem (Preferably compared to others)
- A detailed description of the problem
- A detailed description of how to fix the problem

**Comment by AlbertHald** [comment]
![Image](https://github.com/user-attachments/assets/fc5634d9-2be7-4258-a54a-8521ed874555)

**Comment by NybyDK** [comment]
https://sustainablewebdesign.org/

**Comment by NybyDK** [comment]
Low, Low https://sustainablewebdesign.org/guidelines/3-2-minify-your-html-css-and-javascript/

**Comment by NybyDK** [comment]
Sources have been found, and what needs to be scored has been found
BUT we need scoring system, how 0? how 100? how A? how B?

**Comment by atjn** [comment]
Inspiration:
- https://pagespeed.web.dev/analysis/https-aau-dk/kku8h622r0
- https://securityheaders.com/?q=https%3A%2F%2Fwww.aau.dk
- https://developer.mozilla.org/en-US/observatory/analyze?host=aau.dk
