### ISSUE TITLE
Set up extension backbone

### ISSUE THREAD

**Issue by atjn** [AAU-SW7-PSAAAB/energy-label-extension#2]
The extension needs a core service worker that can start a scan by loading a list of plugins and executing them, then return a result.

This is design and setup for the MVP backbone, then we can create new issues for each feature that it needs to implement.

**Comment by NybyDK** [comment]
Related to #19

**Comment by NybyDK** [comment]
Does Plasmo go brr?

**Comment by NybyDK** [comment]
Plasmo did go brr but then it went zzz
