### ISSUE TITLE
Skriv om format og compression plugin?

### ISSUE THREAD

**Issue by atjn** [AAU-SW7-PSAAAB/energy-label-extension#207]
![Image](https://github.com/user-attachments/assets/afb74716-69cb-4f60-9641-c6a2c64aea33)

**Comment by NybyDK** [comment]
blev vi ikke enige om nej

**Comment by atjn** [comment]
jov tror jeg?

**Comment by NybyDK** [comment]
hallo kan du ikke stoppe med at sende mig mails?

Sent from Gmail

**Comment by atjn** [comment]
Okay beklager

Sent from Github

**Comment by atjn** [comment]
#yeeted
