### ISSUE TITLE
[Extension] Global UI state I local storage

### ISSUE THREAD

**Issue by BaBrixx** [AAU-SW7-PSAAAB/energy-label-extension#60]
Vi ønsker at gemme staten af UI'et på tværs af at man åbner og lukker pop-uppen samt imellem de forskellige views. Vi vil af denne grund implementere en State handler der sætter, opdatere samt getter UI state vha. localstorage.

**Comment by atjn** [comment]
Most of that work is done in #65, but more work is needed to make it work with the UI.
