### ISSUE TITLE
[Extension] Definer strukturen af feedback fra plugins

### ISSUE THREAD

**Issue by BaBrixx** [AAU-SW7-PSAAAB/energy-label-extension#61]
Da vi ønsker at give brugeren specifik feedback der kan bruges til at implementere fikses på de individuelle ting skal vi have defineret hvordan strukturen af denne feedback ser ud for hvert plugin

**Comment by atjn** [comment]
Det er vigtigt at feedback foregår løbende, så vi kan vise det så snart der er noget.
