### ISSUE TITLE
Write end-to-end tests

### ISSUE THREAD

**Issue by atjn** [AAU-SW7-PSAAAB/energy-label-extension#86]
This tracks implementation of E2E tests across the entire plugin. Add your sub-issue here:

- [x] #110
- [x] #132
- [x] #149
- [x] #150
- [ ] #161

**Comment by NybyDK** [comment]
Playwright has been set up in #110

**Comment by atjn** [comment]
Has been? Bold words...

**Comment by NybyDK** [comment]
u are **bold**
