### ISSUE TITLE
Find på navn til extension

### ISSUE THREAD

**Issue by atjn** [AAU-SW7-PSAAAB/energy-label-extension#93]

**Comment by atjn** [comment]
To get your brain going:

1. EcoSurf
Combines "eco" and "surf," suggesting eco-friendly browsing.

2. GreenWebScore
Straightforward and descriptive, indicating a focus on "green" or sustainable web practices.

3. EcoMeter
Suggests measuring eco-friendliness directly, with a focus on the digital environment.

4. EffiScore
Short and catchy, combining "efficiency" and "score."

5. ByteGreen
Plays on "bytes" (digital data) and "green" for environmental impact.

6. EcoSiteCheck
Clear and descriptive, showing that the plugin checks sites for eco-friendliness.

7. GreenGauge
Combines "green" and "gauge," suggesting a tool that measures environmental impact.

8. SustainSurf
Mix of "sustainable" and "surf," hinting at eco-friendly web surfing.

9. EcoRank
Short and powerful, focusing on ranking sites by eco-friendliness.

10. GreenPulse
Suggests that the plugin "takes the pulse" of a website's environmental impact.

11. SiteSage
"Sage" implies wisdom and responsibility, with a focus on eco-conscious browsing.

12. CarbonLite
Highlights carbon footprint reduction, with "lite" implying efficiency.

13. EcoBrowse
Encourages environmentally friendly browsing practices.

14. EnerGauge
A play on "energy gauge," indicating it monitors energy efficiency.

15. WebEcoMeter
Descriptive and straightforward, combining "web" and "eco meter."

16. GreenScreen
Hints at viewing the "green" quality of each website, like a filter.

17. SustaiNet
A mix of "sustainable" and "internet," suggesting eco-friendly net usage.

18. EcoSiteRank
Clear and concise, indicating the ranking of sites by eco-friendliness.

19. EnergiScore
Combines "energy" with "score," suggesting a focus on energy usage.

20. WebWise
Short and catchy, implying wise and sustainable choices for the web.

**Comment by NybyDK** [comment]
"Bob".

**Comment by atjn** [comment]
Thank you all for the great ideas, we chose "Green Machine"
